In [46]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
from scipy import signal

# Davor Jordacevic 2016/201251

In [47]:
# a)
Ac=np.matrix([[-6.,-8.,0.],[1.,0.,0.],[0.,1.,0.]])
Bc=np.matrix([[1.],[0.],[0.]])
Cc=np.matrix([[0.,1.,3.]])
Dc=np.matrix([[0.]])
G=signal.lti(Ac,Bc,Cc,Dc)
print('A:\n',Ac)
print('B:\n',Bc)
print('C:\n',Cc)
print('D:\n',Dc)

A:
 [[-6. -8.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]]
B:
 [[ 1.]
 [ 0.]
 [ 0.]]
C:
 [[ 0.  1.  3.]]
D:
 [[ 0.]]


In [48]:
# b)
Ao=np.matrix([[-6.,1.,0.],[-8.,0.,1.],[0.,0.,0.]])
Bo=np.matrix([[0.],[1.],[3.]])
Co=np.matrix([[1.,0.,0.]])
Do=np.matrix([[0.]])
G=signal.lti(Ao,Bo,Co,Do)
print('A:\n',Ao)
print('B:\n',Bo)
print('C:\n',Co)
print('D:\n',Do)

A:
 [[-6.  1.  0.]
 [-8.  0.  1.]
 [ 0.  0.  0.]]
B:
 [[ 0.]
 [ 1.]
 [ 3.]]
C:
 [[ 1.  0.  0.]]
D:
 [[ 0.]]


In [49]:
#c)
brojilac= np.array([1,3])
imenilac=np.array([1,6,8,0])
r,p,k=signal.residue(brojilac, imenilac)
r,p

(array([-0.125, -0.25 ,  0.375]), array([-4., -2.,  0.]))

In [50]:
#c)
Ad=np.matrix([[p[0],0.,0.],[0.,p[1],0.],[0.,0.,p[2]]])
Bd=np.matrix([[1.],[1.],[1.]])
Cd=np.matrix([[r[0],r[1],r[2]]])
Dd=np.matrix([[0.]])
Gd=signal.lti(Ad, Bd, Cd,Dd)
print('A:\n',Ad)
print('B:\n',Bd)
print('C:\n',Cd)
print('D:\n',Dd)

A:
 [[-4.  0.  0.]
 [ 0. -2.  0.]
 [ 0.  0.  0.]]
B:
 [[ 1.]
 [ 1.]
 [ 1.]]
C:
 [[-0.125 -0.25   0.375]]
D:
 [[ 0.]]


In [51]:
#d)
#Model je kontolabilan ukoliko mu je matrica kontrolabilnosti invertabilna
#Model pod a je sigurno kontrolabilan
CC= np.concatenate((Bo,Ao*Bo),axis=1)
CC*-1
# Model pod b je kontolabilan
CC= np.concatenate((Bd,Ad*Bd),axis=1)
CC*-1
# Model pod c je kontolabilan

#Model je opservabilan ukoliko mu je matrica opservabilnosti invertabilna
#Model pod b je sigurno opservabilan
OB= np.concatenate((Cc,Cc*Ac),axis=0)
OB*-1
# Model pod a je opservabilan
OB= np.concatenate((Cd,Cd*Ad),axis=0)
OB*-1
# Model pod c je opservabilan

matrix([[ 0.125,  0.25 , -0.375],
        [-0.5  , -0.5  ,  0.   ]])