In [1]:
import numpy as np;
import scipy as sp;
import matplotlib.pyplot as plt
from scipy import signal

In [2]:
# Odrediti razvoj u parcijalne razlomske funkcije prenosa: G(s)=(s+10)(s^2+s+25)/s^2(s+3)(s^2+s+36)

In [3]:
brojilac=sp.convolve([1, 10],[1, 1,25])
imenilac=sp.convolve(sp.convolve([1, 0, 0],[1,3]),[1, 1,36])
r,p,k=signal.residue(brojilac, imenilac)

In [4]:
r

array([-0.51183128+0.j        ,  2.31481481+0.j        ,
        0.57407407+0.j        , -0.03112140-0.03146662j,
       -0.03112140+0.03146662j])

In [5]:
p

array([ 0.0+0.j        ,  0.0+0.j        , -3.0+0.j        ,
       -0.5+5.97913037j, -0.5-5.97913037j])

In [6]:
# poslednja dva su konjugovano kompleksna pa ih pakujemo u jedan razlomak
res1=np.array([r[3], -p[4]*r[3]])+np.array([r[4], -p[3]*r[4]])
res1

array([-0.06224280+0.j,  0.34516461+0.j])

In [7]:
# provera imenioca razlomka sa konjugovano kompleksnim polovima:
b=sp.convolve([1, -p[3]],[1, -p[4]])
b

array([  1.+0.j,   1.+0.j,  36.+0.j])

In [8]:
#Finaln razvoj je dakle (r[0]*s+r[1])/s^2 +  r[2]/(s+3)  +  (res1[0]*s+res1[1])/(s^2+s+36)